name: 'Netlify Preview Deploy'

env:
  NODE_OPTIONS: --max-old-space-size=7168

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy-preview:
    name: 'Deploy Preview'
    runs-on: ubuntu-latest

    steps:
      - name: deploy to preview mode
        uses: thundermiracle/netlify-deploy@v1
        env:
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID}}
          GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.GATSBY_ALGOLIA_INDEX_NAME}}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY}}
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
          deploy_dir: "./public"
          build_command: yarn build
          cache_path: |
            .cache
            public
            node_modules
